-- Local dev only. Seeds run after migrations on `supabase start` / `db reset`
-- and are NEVER pushed to the hosted project (web/scripts/migrate.js and
-- `supabase db push` only read supabase/migrations/).
--
-- Nothing here right now. The previous contents were a questions_insert_local_dev
-- policy letting an anonymous session add questions without signing in; anonymous
-- auth was removed and both local and prod now require a real login, so it only
-- served to OR around questions_insert_own's is_anonymous guard.
