-- Generated by `npm run db:schema` from the LOCAL Docker DB. Do not edit, do not apply.

-- Name: inbox_items; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.inbox_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    text text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.inbox_items OWNER TO postgres;

-- Name: inbox_items inbox_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.inbox_items
    ADD CONSTRAINT inbox_items_pkey PRIMARY KEY (id);

-- Name: inbox_items_user_id; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX inbox_items_user_id ON public.inbox_items USING btree (user_id);

-- Name: inbox_items inbox_items_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.inbox_items
    ADD CONSTRAINT inbox_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Name: inbox_items; Type: ROW SECURITY; Schema: public; Owner: postgres

ALTER TABLE public.inbox_items ENABLE ROW LEVEL SECURITY;

-- Name: inbox_items inbox_items_delete_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY inbox_items_delete_own ON public.inbox_items FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: inbox_items inbox_items_insert_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY inbox_items_insert_own ON public.inbox_items FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

-- Name: inbox_items inbox_items_select_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY inbox_items_select_own ON public.inbox_items FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: TABLE inbox_items; Type: ACL; Schema: public; Owner: postgres

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.inbox_items TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.inbox_items TO authenticated;
GRANT ALL ON TABLE public.inbox_items TO service_role;

