-- Generated by `npm run db:schema` from the LOCAL Docker DB. Do not edit, do not apply.

-- Name: progress; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.progress (
    user_id uuid NOT NULL,
    question_id text NOT NULL
);

ALTER TABLE public.progress OWNER TO postgres;

-- Name: progress progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.progress
    ADD CONSTRAINT progress_pkey PRIMARY KEY (user_id, question_id);

-- Name: progress progress_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.progress
    ADD CONSTRAINT progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Name: progress Users can delete their own progress; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY "Users can delete their own progress" ON public.progress FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: progress Users can insert their own progress; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY "Users can insert their own progress" ON public.progress FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

-- Name: progress Users can read their own progress; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY "Users can read their own progress" ON public.progress FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: progress Users can update their own progress; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY "Users can update their own progress" ON public.progress FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

-- Name: progress; Type: ROW SECURITY; Schema: public; Owner: postgres

ALTER TABLE public.progress ENABLE ROW LEVEL SECURITY;

-- Name: TABLE progress; Type: ACL; Schema: public; Owner: postgres

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.progress TO anon;
GRANT ALL ON TABLE public.progress TO authenticated;
GRANT ALL ON TABLE public.progress TO service_role;

