-- Generated by `npm run db:schema` from the LOCAL Docker DB. Do not edit, do not apply.

-- Name: question_position; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.question_position (
    user_id uuid NOT NULL,
    question_id text NOT NULL,
    "position" integer NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.question_position OWNER TO postgres;

-- Name: question_position question_position_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.question_position
    ADD CONSTRAINT question_position_pkey PRIMARY KEY (user_id, question_id);

-- Name: question_position question_position_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.question_position
    ADD CONSTRAINT question_position_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Name: question_position; Type: ROW SECURITY; Schema: public; Owner: postgres

ALTER TABLE public.question_position ENABLE ROW LEVEL SECURITY;

-- Name: question_position question_position_delete_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY question_position_delete_own ON public.question_position FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: question_position question_position_insert_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY question_position_insert_own ON public.question_position FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

-- Name: question_position question_position_select_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY question_position_select_own ON public.question_position FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: question_position question_position_update_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY question_position_update_own ON public.question_position FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: TABLE question_position; Type: ACL; Schema: public; Owner: postgres

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.question_position TO anon;
GRANT ALL ON TABLE public.question_position TO authenticated;
GRANT ALL ON TABLE public.question_position TO service_role;

