-- Generated by `npm run db:schema` from the LOCAL Docker DB. Do not edit, do not apply.

-- Name: question_counts; Type: VIEW; Schema: public; Owner: postgres

CREATE VIEW public.question_counts WITH (security_invoker='true') AS
 SELECT topic,
    file,
    (count(*))::integer AS count
   FROM public.questions
  GROUP BY topic, file;

ALTER VIEW public.question_counts OWNER TO postgres;

-- Name: TABLE question_counts; Type: ACL; Schema: public; Owner: postgres

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.question_counts TO anon;
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.question_counts TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.question_counts TO service_role;

