-- Generated by `npm run db:schema` from the LOCAL Docker DB. Do not edit, do not apply.

-- Name: set_aside_items; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.set_aside_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    title text NOT NULL,
    markdown text NOT NULL,
    body_html text NOT NULL,
    lang text,
    tags text,
    problem text,
    topic text NOT NULL,
    file text NOT NULL,
    label text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.set_aside_items OWNER TO postgres;

-- Name: set_aside_items set_aside_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.set_aside_items
    ADD CONSTRAINT set_aside_items_pkey PRIMARY KEY (id);

-- Name: set_aside_items_user_id; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX set_aside_items_user_id ON public.set_aside_items USING btree (user_id);

-- Name: set_aside_items set_aside_items_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.set_aside_items
    ADD CONSTRAINT set_aside_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Name: set_aside_items; Type: ROW SECURITY; Schema: public; Owner: postgres

ALTER TABLE public.set_aside_items ENABLE ROW LEVEL SECURITY;

-- Name: set_aside_items set_aside_items_delete_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY set_aside_items_delete_own ON public.set_aside_items FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: set_aside_items set_aside_items_insert_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY set_aside_items_insert_own ON public.set_aside_items FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

-- Name: set_aside_items set_aside_items_select_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY set_aside_items_select_own ON public.set_aside_items FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: TABLE set_aside_items; Type: ACL; Schema: public; Owner: postgres

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.set_aside_items TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.set_aside_items TO authenticated;
GRANT ALL ON TABLE public.set_aside_items TO service_role;

