-- Generated by `npm run db:schema` from the LOCAL Docker DB. Do not edit, do not apply.

-- Name: user_settings; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.user_settings (
    user_id uuid NOT NULL,
    default_sort text DEFAULT 'manual'::text NOT NULL,
    remember_filters boolean DEFAULT true NOT NULL,
    theme text DEFAULT 'light'::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    instruction_presets jsonb DEFAULT jsonb_build_array(jsonb_build_object('id', 'default', 'name', 'Default', 'text', '- Lead with a bold key term or topic name and a one-line definition in the same sentence, then expand with bullet points written as complete narrative sentences (not fragments). This is the default format.
- Keep it natural and concise, not padded — use only as many bullets as the topic genuinely needs. If the opening sentence alone fully answers it, that''s enough.
- Bold key technical terms inline within the sentence as they come up — never as a static label like "**Caching:** ...".
- Use an em dash (—) within a bullet to add contrast or elaboration where it reads naturally.
- Switch to a Markdown table only when the content is inherently comparative (e.g. "X vs Y"). Use code blocks only when a code example is genuinely needed.')) NOT NULL,
    active_instruction_preset_id text DEFAULT 'default'::text NOT NULL,
    navigate_after_move boolean DEFAULT false NOT NULL,
    default_priority text DEFAULT 'med'::text,
    CONSTRAINT user_settings_default_priority_check CHECK ((default_priority = ANY (ARRAY['high'::text, 'med'::text, 'low'::text])))
);

ALTER TABLE public.user_settings OWNER TO postgres;

-- Name: user_settings user_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_pkey PRIMARY KEY (user_id);

-- Name: user_settings user_settings_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Name: user_settings Users can manage own settings; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY "Users can manage own settings" ON public.user_settings TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: user_settings; Type: ROW SECURITY; Schema: public; Owner: postgres

ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- Name: TABLE user_settings; Type: ACL; Schema: public; Owner: postgres

GRANT ALL ON TABLE public.user_settings TO anon;
GRANT ALL ON TABLE public.user_settings TO authenticated;
GRANT ALL ON TABLE public.user_settings TO service_role;

